[package]
name = "windows"
version = "0.1.0"
edition = "2021"

[dependencies]
raylib-sys = { path = "../../raylib-rs/raylib-sys" }
crossy_multi_core = { path = "../core" }
serde_json = "1.0.133"
serde = "1.0.215"
froggy-rand = "0.2.1"
