[package]
name = "crossy_multi_gm_client"
version = "0.1.0"
authors = ["Dan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
crossy_multi_core = { path = "../core" }

[lib]
crate-type = ["cdylib"]